### ISSUE TITLE
Error: Unregistered "default" with name "[object Object]"

### ISSUE THREAD

**Issue by mariohmol** [topliceanu/mongoose-gen#23]
Hi there,

thanks a lot for this repo!

I`m trying to use this repo following the swagger api example, Swagger Petstore

They have a data like:

```js
{
  photoUrls: [ 'photoUrls', 'photoUrls' ],
  name: 'doggie',
  id: 0,
  category: { name: 'name', id: 6 },
  tags: [ { name: 'name', id: 1 }, { name: 'name', id: 1 } ],
  status: 'available',
  default: {
    photoUrls: [ 'photoUrls', 'photoUrls' ],
    name: 'doggie',
    id: 0,
    category: { name: 'name', id: 6 },
    tags: [ [Object], [Object] ],
    status: 'available'
  }
}
```

And getting this error:

Error pet Error: Unregistered "default" with name "[object Object]"
    at get (/Users/mariohmol/projetos/mean-crud-generator/node_modules/mongoose-gen/lib/generator.js:53:15)
    at Object.<anonymous> (/Users/mariohmol/projetos/mean-crud-generator/node_modules/mongoose-gen/lib/generator.js:149:20)
    at JSON.parse (<anonymous>)
    at Object.convert (/Users/mariohmol/projetos/mean-crud-generator/node_modules/mongoose-gen/lib/generator.js:135:24)
    at Object.<anonymous> (/Users/mariohmol/projetos/mean-crud-generator/backend/model.ts:41:56)
    at step (/Users/mariohmol/projetos/mean-crud-generator/backend/model.ts:32:23)
    at Object.next (/Users/mariohmol/projetos/mean-crud-generator/backend/model.ts:13:53)
    at fulfilled (/Users/mariohmol/projetos/mean-crud-generator/backend/model.ts:4:58)

Ideas?

Thanks

**Comment by mariohmol** [comment]
i got it.. its not from a data example
